feat(metamorpheus-converter): Add clean functionality of metamorpheus converter
Vitek-Lab/MSstatsConvert pull request #83
Opened 2024-01-10 16:00 UTC by tonywu1999

## Description

As a part of this [issue](https://github.com/Vitek-Lab/MSstatsPTM/issues/48), users are requesting a converter from Metamorpheus to MSstatsPTM.  

The first step is to create a converter from Metamorpheus to MSstats.

## Changes

1. Set up implementation for MSstatsClean for Metamorpheus
2. Added annotation data from Metamorpheus into raw data folder
3. Added RDS file of MSstatsInputFiles object of Metamorpheus input data into raw data folder
4. Adjusted documentation via `devtools::document()`

## Testing
1. Verified that MSstatsClean works as expected for Metamorpheus input
2. Added unit tests verifying MSstatsClean works as expected for Metamorpheus input
3. Installed and ran RStudio check locally and everything succeeds.

## Next Steps
1. Squash & Merge
2. Create MetamorpheusToMSstats function in the core MSstats package

2024-01-10 20:28 UTC, tonywu1999 commented on inst/tinytest/raw_data/Metamorpheus/ExperimentalDesign.tsv
> +Run	Condition	BioReplicate	Fraction	Techrep
First column doesn't necessarily need to be run

2024-01-10 20:29 UTC, tonywu1999 commented on inst/tinytest/raw_data/Metamorpheus/ExperimentalDesign.tsv
> +NEG2-calib	neg	2	1	1
This is something that Metamorpheus doesn't necessarily do correctly where they give different bioreplicates the same ID (1 & 2) - MSstats thinks of this as a paired design.  Change the ID.

2024-01-10 20:29 UTC, tonywu1999 commented on inst/tinytest/raw_data/Metamorpheus/ExperimentalDesign.tsv
> +POS2-calib	pos	2	1	1
Rename "ExperimentalDesign" to "Annotation.tsv" to not mislead people to think this file comes from Metamorpheus.

2024-01-10 20:32 UTC, tonywu1999 commented on inst/tinytest/raw_data/Metamorpheus/ExperimentalDesign.tsv
> +Run	Condition	BioReplicate	Fraction	Techrep
We need to add validation that the join is possible, and better report the explanation (rather than a join error).

2024-01-10 20:33 UTC, tonywu1999 commented on inst/tinytest/raw_data/Metamorpheus/ExperimentalDesign.tsv
> +Run	Condition	BioReplicate	Fraction	Techrep
Remove Techrep

2024-01-10 20:35 UTC, devonjkohler commented
Looks good!

2024-01-10 20:40 UTC, devonjkohler approved these changes
Looks good! We can merge this in if Matt doesn't have any changes.

2024-01-12 12:35 UTC, mstaniak commented on inst/tinytest/raw_data/Metamorpheus/AllQuantifiedPeaks.rds
Why rds rather than a text file?

2024-01-12 12:36 UTC, mstaniak requested changes
Looks good, only question is about the rds format.

2024-01-12 14:51 UTC, tonywu1999 commented on inst/tinytest/raw_data/Metamorpheus/AllQuantifiedPeaks.rds
@mstaniak 

I used an RDS file for unit testing purposes.  

The output of the MSstatsImport function is an MSstatsMetamorpheusFiles object, and I wanted to use that object as the input of MSstatsClean for unit tests.  At the same time, I wanted to test MSstatsClean independently from other functions.  As a result, I saved the object as an RDS file and read the RDS file as input for unit tests.

2024-01-12 16:02 UTC, tonywu1999 commented on inst/tinytest/raw_data/Metamorpheus/AllQuantifiedPeaks.rds
To make things less confusing, I'll change the name of the RDS file to be something like "MSstatsMetamorpheusFilesObject.rds" to make it clear it's an object of class MSstatsMetamorpheusFiles and has nothing to do with the output of Metamorpheus directly.

2024-01-17 15:19 UTC, merged